{ lib, pkgs, ... }:

let
  pamLib = "${pkgs.pam}/lib/security";
  fpSo   = "${pkgs.fprintd}/lib/security/pam_fprintd.so";
  kwSo   = "${pkgs.kdePackages.kwallet-pam}/lib/security/pam_kwallet5.so";

  flockArgs = "deny=2 unlock_time=0";  # 2 failures → locked until `faillock --user nico --reset`

  # ── KDE lock screen authentication (Option A) ──────────────────────────────
  # Plasma 6's locker drives THREE parallel PAM services, and unlocks on the
  # first one that succeeds:
  #   kde             → password        (this stack: password AND fingerprint)
  #   kde-fingerprint → fingerprint     (DENIED below — fp must never unlock alone)
  #   kde-smartcard   → YubiKey PIV     (auto-generated by security.pam.p11 → pam_p11)
  #
  # Effective policy:  YubiKey-PIV  OR  (password THEN fingerprint).
  # Fingerprint is treated as a mandatory 2nd factor, never a standalone key,
  # because the libfprint/Goodix path is not a trustworthy sole factor.
  #
  # faillock counts a wrong password OR a bad swipe. After 2 it locks; the
  # rescue paths while locked are the YubiKey PIV (on the lock screen itself)
  # or a TTY password login (Ctrl+Alt+F2) followed by `faillock --user nico --reset`.
  kdeAuthText = ''
    auth required     ${pamLib}/pam_faillock.so preauth silent ${flockArgs}
    auth [success=1 default=bad] ${pamLib}/pam_unix.so likeauth try_first_pass
    auth [default=die]           ${pamLib}/pam_faillock.so authfail
    auth [success=1 default=bad] ${fpSo} timeout=10
    auth [default=die]           ${pamLib}/pam_faillock.so authfail
    auth optional     ${kwSo}
    auth sufficient   ${pamLib}/pam_faillock.so authsucc
    auth required     ${pamLib}/pam_deny.so

    account required  ${pamLib}/pam_faillock.so
    account required  ${pamLib}/pam_unix.so

    password sufficient ${pamLib}/pam_unix.so nullok yescrypt

    session required  ${pamLib}/pam_unix.so
    session optional  ${kwSo}
  '';

  # Standalone fingerprint method: always deny, so a swipe by itself can never
  # unlock the screen. The reader is only honoured as the 2nd factor in `kde`.
  fpDenyText = ''
    auth     required ${pamLib}/pam_deny.so
    account  required ${pamLib}/pam_unix.so
    password required ${pamLib}/pam_deny.so
    session  required ${pamLib}/pam_unix.so
  '';
in

{
  # FIDO2/U2F stays global: LUKS boot unlock, sudo, and TTY login still use it.
  security.pam.u2f = {
    enable   = true;
    settings = {
      authfile = "/etc/nixos/secrets/u2f-mappings";
      cue      = true;
    };
  };

  # YubiKey PIV / PKCS#11. Enabling this makes the Plasma module emit the
  # `kde-smartcard` lock-screen method (pam_p11, control "sufficient"), which
  # authenticates against ~/.eid/authorized_certificates via opensc-pkcs11.
  # It also becomes an accepted factor for sudo / login / sddm.
  security.pam.p11.enable = true;

  # Lock screen: Plasma 6 uses the `kde` service (not `kscreenlocker`).
  security.pam.services.kde.text             = lib.mkForce kdeAuthText;
  security.pam.services.kde-fingerprint.text = lib.mkForce fpDenyText;

  # The smartcard (YubiKey PIV) method must be YubiKey-only. Drop the pam_unix
  # that NixOS adds by default, so a password can never slip in via this track.
  security.pam.services.kde-smartcard.unixAuth = lib.mkForce false;
}
